version: "3.7"

networks:
  FPI.network:
    driver: bridge

services:
  php:
    build: ./docker/php
    restart: always
    tty: true
    container_name: FPI.php
    networks:
      - FPI.network
    ports:
      - "8001:8001"
    volumes:
      - .:/var/www/app.dev

  #nginx:
  #  build: ./docker/nginx
  #  container_name: FPI.nginx
  #  restart: always
  #  tty: true
  #  depends_on:
  #    - php
      # - mysql
  #  ports:
  #    - "80:80"
  #    - "433:433"
  #  volumes:
  #    - .:/var/www/app.dev
  #  networks:
  #   - FPI.network

  apache:
    build: ./docker/apache
    restart: always
    container_name: FPI.apache
    networks:
      - FPI.network
    depends_on:
      - php
       # - mysql
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/app.dev


  # mysql:
  #   build: ./docker/mysql
  #   tty: true
  #   restart: always
  #   container_name: FPI.mysql
  #   networks:
  #     - FPI.network
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - "./docker/mysql/config/mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro"
  #     - "./docker/mysql/dbdata:/var/lib/mysql"
  #   environment:
  #     - MYSQL_PASSWORD=root
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=development

  #  phpmyadmin:
  #    image: library/phpmyadmin
  #    container_name: FPI.phpmyadmin
  #    tty: true
  #    networks:
  #      - FPI.network
  #    depends_on:
  #      - mysql
  #      - mariadb
  #    environment:
  #      PMA_USER: root
  #      PMA_PASSWORD: root
  #      PMA_HOSTS: mysql,mariadb
  #      PMA_PORT: 3306
  #      PMA_ARBITRARY: 1
  #    ports:
  #      - '8080:80'

